
image:
  file: .gitpod/Dockerfile

tasks:
  - name: Install GraalJVM 21 (via SDKMAN!)
    before: rm -rf ~/.sdkman && curl -s "https://get.sdkman.io" | bash
    command: sdk install java 21.0.5-graal

ports:
  - port: 6080
    visibility: private
    name: Desktop

vscode:
  extensions:
    - vscjava.vscode-java-pack

